name: rust nightly

on:
    repository_dispatch:
        types: nightly-release
    schedule:
        - cron: '0 2 * * *'

jobs:
    generate-build-number:
        runs-on: ubuntu-16.04
        steps:
            - name: Generate build number
              uses: einaregilsson/build-number@v2
              id: buildnumber
              with:
                  token: ${{ secrets.github_token }}
                  prefix: rust

            - name: Upload build number
              uses: actions/upload-artifact@v1
              with:
                  name: BUILD_NUMBER
                  path: BUILD_NUMBER

    build:
        needs: generate-build-number
        runs-on: ubuntu-16.04
        strategy:
            fail-fast: true
            matrix:
                platform-version: [ 193, 201 ]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Download build number
              uses: actions/download-artifact@v1
              with:
                  name: BUILD_NUMBER

            - name: Restore build number
              id: buildnumber
              uses: einaregilsson/build-number@v2

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build & publish
              env:
                  CI: true
                  ORG_GRADLE_PROJECT_buildNumber: ${{ steps.buildnumber.outputs.build_number }}
                  ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}
                  ORG_GRADLE_PROJECT_enableBuildSearchableOptions: true
                  ORG_GRADLE_PROJECT_publishChannel: nightly
                  ORG_GRADLE_PROJECT_publishToken: ${{ secrets.plugin_bot_token }}
              run: ./gradlew :plugin:buildPlugin :plugin:publishPlugin
